from .weighted_switch import (
    NODE_CLASS_MAPPINGS as PRIMARY_NODE_CLASS_MAPPINGS,
    NODE_DISPLAY_NAME_MAPPINGS as PRIMARY_NODE_DISPLAY_NAME_MAPPINGS,
)

from .weighted_conditional_switch import (
    NODE_CLASS_MAPPINGS as SECONDARY_NODE_CLASS_MAPPINGS,
    NODE_DISPLAY_NAME_MAPPINGS as SECONDARY_NODE_DISPLAY_NAME_MAPPINGS,
)

NODE_CLASS_MAPPINGS = {
    **PRIMARY_NODE_CLASS_MAPPINGS,
    **SECONDARY_NODE_CLASS_MAPPINGS,
}

NODE_DISPLAY_NAME_MAPPINGS = {
    **PRIMARY_NODE_DISPLAY_NAME_MAPPINGS,
    **SECONDARY_NODE_DISPLAY_NAME_MAPPINGS,
}

__all__ = ['NODE_CLASS_MAPPINGS', 'NODE_DISPLAY_NAME_MAPPINGS']
